name: Package APP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install ember
        run: yarn global add ember-cli

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install electron dependencies
        run: cd electron-app && yarn install --frozen-lockfile && cd ..

      - name: Build project
        run: yarn run make-exe

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ./electron-app/out/make/squirrel.windows/x64/acc-results-json-to-csv-* Setup.exe
